"""Noqlen Aria Core public MVP surface."""

from noqlen_aria.anchor_adapter import AnchorControlClient
from noqlen_aria.contracts import (
    AriaError,
    AriaResult,
    AriaWarning,
    ControlClient,
    DiagnosticsViewState,
    FakeControlClient,
    LibraryViewState,
    LifecycleIntent,
    PermissionState,
    ReadinessViewState,
    ServerViewState,
    StorageAccessState,
    safe_serialize,
    sanitize_text,
)
from noqlen_aria.library import (
    AlbumSummary,
    ArtistSummary,
    FolderSummary,
    GenreSummary,
    LibraryBrowseCategory,
    LibraryBrowseRequest,
    LibraryBrowseResult,
    LibraryBrowseService,
    LibraryItemSummary,
    LibrarySearchQuery,
    LibrarySearchResult,
    LibrarySearchService,
    PlaylistSummary,
    TrackSummary,
)
from noqlen_aria.services import (
    DiagnosticsService,
    LifecycleIntentPreview,
    LifecycleIntentService,
    ReadinessService,
    ResultMappingService,
    StatusService,
)

__version__ = "0.0.0"

__all__ = [
    "__version__",
    "AnchorControlClient",
    "AlbumSummary",
    "AriaError",
    "AriaResult",
    "AriaWarning",
    "ArtistSummary",
    "ControlClient",
    "DiagnosticsService",
    "DiagnosticsViewState",
    "FakeControlClient",
    "FolderSummary",
    "GenreSummary",
    "LibraryViewState",
    "LibraryBrowseCategory",
    "LibraryBrowseRequest",
    "LibraryBrowseResult",
    "LibraryBrowseService",
    "LibraryItemSummary",
    "LibrarySearchQuery",
    "LibrarySearchResult",
    "LibrarySearchService",
    "LifecycleIntent",
    "LifecycleIntentPreview",
    "LifecycleIntentService",
    "PermissionState",
    "PlaylistSummary",
    "ReadinessService",
    "ReadinessViewState",
    "ResultMappingService",
    "ServerViewState",
    "StatusService",
    "StorageAccessState",
    "TrackSummary",
    "safe_serialize",
    "sanitize_text",
]
